Revert "copy deps.proto from bazel source and use it instead of @bazel_tools//... so that 9.x works" - fails in 7.x with whatever cc toolchain is default when compiling prorobuf
ERROR: /home/runner/.bazel/external/protobuf~/upb_generator/minitable/BUILD:64:11: Compiling upb_generator/minitable/names.cc [for tool] failed: (Exit 1): gcc failed: error executing CppCompile command (from target @@protobuf~//upb_generator/minitable:names) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/protobuf~/upb_generator/minitable/names.h:16,
                 from external/protobuf~/upb_generator/minitable/names.cc:8:
external/protobuf~/upb/port/def.inc:33:2: error: #error upb requires C99 or C++17 or MSVC >= 2015.
   33 | #error upb requires C99 or C++17 or MSVC >= 2015.
      |  ^~~~~